---
default: False

# Exceptions, example given, MD045
# MD045: false # allow image with no tag

# Unordered list indentation
MD007:
    # Spaces for indent
    indent: 2
# Unordered list style
MD004: False
# In-line HTML.
MD033:
    allowed_elements:
    - "br"
    - "code"
    - "img"
# Line lengths
MD013:
    line_length: 80
    tables: False
# First line in a file should be a top-level heading
MD041: False
# Punctuation in headers
MD026:
  punctuation: ".,;:。，；："
